services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'lapwingwire'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
