// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// OIDCConfig is the predicate function for oidcconfig builders.
type OIDCConfig func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
